export const routes = {
  HOME: "/",
  KAWASANKU: "/dashboard/kawasanku",
  GDP: "/dashboard/gdp",
  LABOUR_MARKET: "/dashboard/labour-market",
  COMPOSITE_INDEX: "/dashboard/composite-indices",
  WHOLESALE_RETAIL: "/dashboard/wholesale-retail-trade",
  INDUSTRIAL_PRODUCTION: "/dashboard/industrial-production",
  CONSUMER_PRICES: "/dashboard/consumer-prices",
  PRODUCER_PRICES: "/dashboard/producer-prices",
  PUBLICATIONS: "/publications",
  IIP: "/dashboard/international-investment-position",
  LABOUR_PRODUCTIVITY: "dashboard/labour-productivity",
  BOP: "/dashboard/balance-of-payments",
  MANUFACTURING_STATISTICS: "/dashboard/manufacturing-statistics",
} as const;
