export const routes = {
  HOME: "/",
  KAWASANKU: "/dashboard/kawasanku",
  GDP: "/dashboard/gdp",
  LABOUR_MARKET: "/dashboard/labour-market",
  COMPOSITE_INDEX: "/dashboard/composite-indices",
  WHOLESALE_RETAIL: "/dashboard/wholesale-retail-trade",
  INDUSTRIAL_PRODUCTION: "/dashboard/industrial-production",
  CONSUMER_PRICES: "/dashboard/consumer-prices",
  PRODUCER_PRICES: "/dashboard/producer-prices",
  PUBLICATIONS: "/publications",
  IIP: "/dashboard/international-investment-position",
  LABOUR_PRODUCTIVITY: "dashboard/labour-productivity",
  BOP: "/dashboard/balance-of-payments",
  MANUFACTURING_STATISTICS: "/dashboard/manufacturing-statistics",
  CONSTRUCTION_STATISTICS: "/dashboard/construction-statistics",
  FORMAL_SECTOR_WAGES: "/dashboard/formal-sector-wages",
  SERVICES_STATISTICS: "/dashboard/services-statistics",
  SERVICES_PRODUCER_PRICES: "/dashboard/services-producer-prices",
  POPULATION: "/dashboard/population",
  HOUSEHOLD_INCOME_EXPENDITURE: "/dashboard/household-income-expenditure",
  EXCHANGE_RATE: "/dashboard/exchange-rates",
  EXTERNAL_TRADE: "/dashboard/external-trade",
} as const;
