export const routes = {
  HOME: "/",
  KAWASANKU: "/kawasanku",
  GDP: "/gdp",
  LABOUR_MARKET: "/labour-market",
  COMPOSITE_INDEX: "/composite-indices",
  WHOLESALE_RETAIL: "/wholesale-retail-trade",
  INDUSTRIAL_PRODUCTION: "/industrial-production",
  CONSUMER_PRICES: "/consumer-prices",
  PRODUCER_PRICES: "/producer-prices",
  RUBBER: "/rubber",
  CURRENCY_IN_CIRCULATION: "/currency-in-circulation",
  MONEY_SUPPLY: "/money-supply",
  RESERVE_MONEY: "/reserve-money",
  INTERNATIONAL_RESERVES: "/international-reserves",
  INTEREST_RATES: "/interest-rates",
  CRIME: "/violent-property-crime",
  DRUG: "/drug-addiction",
  EXCHANGE_RATE: "/exchange-rates",
} as const;
