import "./globals.css";
import Layout from "components/Layout";
import font from "config/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={font.body.className}>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
