name: E2E Tests
on:
  push:
    branches: [main, staging, feat/e2e-ci]
  pull_request:
    branches: [main, staging]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0 # https://github.com/patrickedqvist/wait-for-vercel-preview
        id: waitForDeploy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
          allow_inactive: true
          environment: Preview - datagovmy-front
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: yarn playwright install chromium
      - name: Run Playwright tests
        run: yarn e2e:vercel
        env:
          CI: true
          BASE_URL: ${{ steps.waitForDeploy.outputs.url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
